FROM python:3.8-slim-buster
COPY . /app
WORKDIR /app
RUN apt-get update && apt-get install -y git ninja-build libglib2.0-0 libsm6 libxrender-dev libxext6 libgl1-mesa-glx \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt
CMD ["gunicorn", "--conf", "gunicorn_conf.py", "webapp:app"] 
