FROM python:3.8-slim-buster
COPY . /app
WORKDIR /app
RUN apt-get update && apt-get install -y libgl1-mesa-glx ffmpeg libsm6 libxext6
RUN pip install -r requirements.txt
CMD ["gunicorn", "--conf", "gunicorn_conf.py", "webapp:app"]